/* reset password, check if user logged in iron session 
if logged in get user id for session and update password by userid and checking existing password and new password and confirm password
if not logged in check for token in request body and verify token and get user id from token and update password by userid and new password and confirm password
token is valid for 4 hours and is generated by creating hmac of user id and timestamp and signing it with a secret key and encoding it in base64url format

*/
import { neon } from '@neondatabase/serverless';
import { verifyAltchaToken } from '@/app/lib/altcha';
import { verifyPassword, hashPassword } from '@/app/lib/utilities';
import { getIronSession } from "iron-session";
import { cookies } from "next/headers";
import { sessionOptions, SessionData } from "@/app/lib/session";

type ResetPasswordBody = {
    newPassword: string;
    confirmPassword: string;
    token?: string;
    currentPassword?: string;
    altcha: string;
};
export async function POST(request: Request) {
    const session = await getIronSession<SessionData>(await cookies(), sessionOptions);
    try {
        const { newPassword, confirmPassword, token, currentPassword, altcha } = (await request.json()) as ResetPasswordBody;
        if (newPassword !== confirmPassword) {
            return Response.json({ message: 'New password and confirm password do not match' }, { status: 400 });
        }
        if (!newPassword || !confirmPassword) {
            return Response.json({ message: 'New password and confirm password are required' }, { status: 400 });
        }
        if (!altcha) {
            return Response.json({ message: 'Altcha verification is required' }, { status: 400 });
        }
        const databaseUrl = process.env.DATABASE_URL;
        if (!databaseUrl) {
            return Response.json({ message: 'DATABASE_URL is not configured' }, { status: 500 });
        }
        // Verify Altcha token
        const altchaResult = await verifyAltchaToken(altcha);
        if (!altchaResult.isValid) {
            return Response.json({ message: altchaResult.error ?? 'Invalid ALTCHA token' }, { status: 400 });
        }

        const sql = neon(databaseUrl);

        let userId: number | "expired" | null = null;
        if (session.isLoggedIn && session.userId) {
            userId = session.userId;
            if (!currentPassword) {
                return Response.json({ message: 'Current password is required' }, { status: 400 });
            }
            const userRows = (await sql`
                SELECT password_hash FROM users
                WHERE id = ${userId}
                LIMIT 1;
            `) as Array<{ password_hash: string }>;
            if (!userRows[0] || !(await verifyPassword(currentPassword, userRows[0].password_hash))) {
                return Response.json({ message: 'Current password is incorrect' }, { status: 401 });
            }
        } else {
            if (!token) {
                return Response.json({ message: 'Token is required' }, { status: 400 });
            }
            userId = await getUserIdFromTokeninDB(token, sql);

            if (userId === "expired") {
                return Response.json({ message: 'Token has expired, please request a new password reset link' }, { status: 400 });
            }
            if (!userId) {
                return Response.json({ message: 'Invalid token, please request a new password reset link' }, { status: 400 });
            }
            await sql`
                    DELETE FROM password_reset_tokens
                    WHERE user_id = ${userId};
                `;
        }
        const newPasswordHash = await hashPassword(newPassword);
        await sql`
            UPDATE users
            SET password_hash = ${newPasswordHash}, updated_at = NOW()
            WHERE id = ${userId};
        `;
        return Response.json({ message: 'Password has been reset successfully' }, { status: 200 });

    } catch (error) {
        return Response.json({ message: 'An error occurred' }, { status: 500 });
    }
}
async function getUserIdFromTokeninDB(token: string, sql: any): Promise<number | "expired" | null> {
    try {
        const tokenRows = (await sql`
            SELECT user_id, expires_at FROM password_reset_tokens
            WHERE token = ${token}
            LIMIT 1;
        `) as Array<{ user_id: number; expires_at: string }>;
        if (tokenRows[0]) {
            const tokenRow = tokenRows[0];
            if (new Date(tokenRow.expires_at) < new Date()) {
                return "expired";
            }
            return tokenRow.user_id;
        }
        return null;
    } catch (error) {
        return null;
    }
}
